version: 2

references:
    pin-npm-version: &pin-npm-version
        run:
            name: Pin NPM to specified version
            command: sudo npm install -g npm@6.13.4

jobs:
    test:
        docker:
            - image: circleci/node:12

        steps:
            - *pin-npm-version
            - checkout

            - restore_cache:
                  keys:
                      - jscache-{{ checksum "package.json" }}
                      - jscache-

            - run: npm ci

            - save_cache:
                  paths:
                      - node_modules
                  key: jscache-{{ checksum "package.json" }}

            - run: npm run test
            - store_test_results:
                  path: test-results

    lint:
        docker:
            - image: circleci/node:12

        steps:
            - *pin-npm-version
            - checkout

            - restore_cache:
                  keys:
                      - jscache-{{ checksum "package.json" }}
                      - jscache-

            - run: npm ci

            - save_cache:
                  paths:
                      - node_modules
                  key: jscache-{{ checksum "package.json" }}

            - run: npm run lint

    check-build:
        docker:
            - image: circleci/node:12

        steps:
            - *pin-npm-version
            - checkout

            - restore_cache:
                  keys:
                      - jscache-{{ checksum "package.json" }}
                      - jscache-

            - run: npm ci

            - save_cache:
                  paths:
                      - node_modules
                  key: jscache-{{ checksum "package.json" }}

            - run: npm run build-ts
            - run: git diff --quiet || (echo 'build does not match' && exit 1)

    publish:
        docker:
            - image: circleci/node:12

        steps:
            - *pin-npm-version
            - checkout
            - add_ssh_keys:
                  fingerprints:
                      - 'ba:c3:f4:48:21:3a:c5:6b:b2:d9:06:e8:bc:ba:7b:e3'

            - run:
                  name: Set branch environemnt variable
                  command: |
                      echo '(echo "$CIRCLE_TAG" | grep -Eq  ^.*-rc.*$) && export BRANCH=$(echo "$CIRCLE_TAG" | sed "s/^v//" | sed "s/-rc.*//") || export BRANCH="master"' >> $BASH_ENV
                      source $BASH_ENV
            - run: npm version --no-git-tag-version ${CIRCLE_TAG}
            - run: git add package.json package-lock.json
            - run: git commit -m "Automatic NPM version bump ${CIRCLE_TAG}"
            - run: git checkout -b temp
            - run: git push origin temp:$BRANCH
            - run: npm config set '//registry.npmjs.org/:_authToken' '${NPM_TOKEN}'
            - run: npm publish --access public

    publish-hot:
        docker:
            - image: circleci/node:12

        steps:
            - *pin-npm-version
            - checkout
            - run: npm version --no-git-tag-version ${CIRCLE_TAG}
            - run: npm config set '//registry.npmjs.org/:_authToken' '${NPM_TOKEN}'
            - run: npm publish --access public

workflows:
    version: 2
    test-and-publish:
        jobs:
            - test
            - lint
            - check-build
            - publish:
                  context: npm-publish
                  requires:
                      - test
                      - lint
                      - check-build
                  filters:
                      tags:
                          only: /^v[0-9]+(\.[0-9]+)*(-rc\.[0-9]*)*/
                      branches:
                          ignore: /.*/
            - publish-hot:
                  context: npm-publish
                  requires:
                      - test
                      - lint
                      - check-build
                  filters:
                      tags:
                          only: /^v[0-9]+(\.[0-9]+)*-hot/
                      branches:
                          ignore: /.*/
